name:                confdump
version:             0.1.0.0
github:              "peteryland/confdump"
license:             BSD3
author:              "Pete Ryland"
maintainer:          "pdr@pdr.cx"
copyright:           "(c) 2019 Pete Ryland"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Tools

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peteryland/confdump#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- directory >= 1.3
- filepath >= 1.4
- html-entities >= 1.0
- io-streams >= 1.5
- mysql-haskell >= 0.8
- parsec >= 3.0
- sorted-list >= 0.2
- text >= 1.2
- transformers >= 0.5
- utf8-string >= 1.0

library:
  source-dirs: src

executables:
  confdump:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confdump

tests:
  confdump-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confdump
